In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [4]:
data = pd.read_csv(r"C:\Users\spars\OneDrive\Desktop\ADM final term\creditcard_2023.csv")
data.head(10)

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-0.260648,-0.469648,2.496266,-0.083724,0.129681,0.732898,0.519014,-0.130006,0.727159,...,-0.110552,0.217606,-0.134794,0.165959,0.126280,-0.434824,-0.081230,-0.151045,17982.10,0
1,1,0.985100,-0.356045,0.558056,-0.429654,0.277140,0.428605,0.406466,-0.133118,0.347452,...,-0.194936,-0.605761,0.079469,-0.577395,0.190090,0.296503,-0.248052,-0.064512,6531.37,0
2,2,-0.260272,-0.949385,1.728538,-0.457986,0.074062,1.419481,0.743511,-0.095576,-0.261297,...,-0.005020,0.702906,0.945045,-1.154666,-0.605564,-0.312895,-0.300258,-0.244718,2513.54,0
3,3,-0.152152,-0.508959,1.746840,-1.090178,0.249486,1.143312,0.518269,-0.065130,-0.205698,...,-0.146927,-0.038212,-0.214048,-1.893131,1.003963,-0.515950,-0.165316,0.048424,5384.44,0
4,4,-0.206820,-0.165280,1.527053,-0.448293,0.106125,0.530549,0.658849,-0.212660,1.049921,...,-0.106984,0.729727,-0.161666,0.312561,-0.414116,1.071126,0.023712,0.419117,14278.97,0
5,5,0.025302,-0.140514,1.191138,-0.707979,0.430490,0.458973,0.611050,-0.092629,0.180811,...,-0.187739,-0.538518,-0.050465,-0.631553,-0.456480,0.252670,0.066681,0.095812,6901.49,0
6,6,1.016482,-0.397181,0.497868,-0.144463,0.331022,0.629243,0.431262,-0.134007,0.796159,...,-0.171137,-0.287017,-0.178197,-1.297597,1.182503,-0.604228,-0.198163,-0.087619,18954.45,0
7,7,-0.051306,-0.007194,1.139941,-0.877880,0.684668,0.714326,0.892615,-0.908409,0.901938,...,0.620676,-0.920426,0.034660,-1.091527,-0.742075,-0.104863,-1.382522,-2.748268,12298.23,0
8,8,-0.130680,-0.349547,0.425786,-0.760444,1.702777,2.324816,0.568968,0.049100,0.273118,...,-0.132787,-0.284700,-0.227779,2.248754,0.534846,-0.929738,-0.224385,0.243790,22052.90,0
9,9,0.058419,-0.093507,1.117270,-0.735172,0.466111,0.332371,0.683425,-0.136674,0.096409,...,-0.203634,-0.601581,-0.145082,-0.654783,-0.196621,0.226818,0.057119,0.100629,210.35,0

In [5]:
print(data.dtypes)

id          int64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object

In [6]:
print(data.isnull().sum(),'\n')
print(data.isnull().sum().any(),'\n')

id        0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

False

In [7]:
data.describe()

,id,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,568630.000000,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,...,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,5.686300e+05,568630.000000,568630.0
mean,284314.500000,-5.638058e-17,-1.319545e-16,-3.518788e-17,-2.879008e-17,7.997245e-18,-3.958636e-17,-3.198898e-17,2.109273e-17,3.998623e-17,...,4.758361e-17,3.948640e-18,6.194741e-18,-2.799036e-18,-3.178905e-17,-7.497417e-18,-3.598760e-17,2.609101e-17,12041.957635,0.5
std,164149.486121,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,...,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,6919.644449,0.5
min,0.000000,-3.495584e+00,-4.996657e+01,-3.183760e+00,-4.951222e+00,-9.952786e+00,-2.111111e+01,-4.351839e+00,-1.075634e+01,-3.751919e+00,...,-1.938252e+01,-7.734798e+00,-3.029545e+01,-4.067968e+00,-1.361263e+01,-8.226969e+00,-1.049863e+01,-3.903524e+01,50.010000,0.0
25%,142157.250000,-5.652859e-01,-4.866777e-01,-6.492987e-01,-6.560203e-01,-2.934955e-01,-4.458712e-01,-2.835329e-01,-1.922572e-01,-5.687446e-01,...,-1.664408e-01,-4.904892e-01,-2.376289e-01,-6.515801e-01,-5.541485e-01,-6.318948e-01,-3.049607e-01,-2.318783e-01,6054.892500,0.0
50%,284314.500000,-9.363846e-02,-1.358939e-01,3.528579e-04,-7.376152e-02,8.108788e-02,7.871758e-02,2.333659e-01,-1.145242e-01,9.252647e-02,...,-3.743065e-02,-2.732881e-02,-5.968903e-02,1.590123e-02,-8.193162e-03,-1.189208e-02,-1.729111e-01,-1.392973e-02,12030.150000,0.5
75%,426471.750000,8.326582e-01,3.435552e-01,6.285380e-01,7.070047e-01,4.397368e-01,4.977881e-01,5.259548e-01,4.729905e-02,5.592621e-01,...,1.479787e-01,4.638817e-01,1.557153e-01,7.007374e-01,5.500147e-01,6.728879e-01,3.340230e-01,4.095903e-01,18036.330000,1.0
max,568629.000000,2.229046e+00,4.361865e+00,1.412583e+01,3.201536e+00,4.271689e+01,2.616840e+01,2.178730e+02,5.958040e+00,2.027006e+01,...,8.087080e+00,1.263251e+01,3.170763e+01,1.296564e+01,1.462151e+01,5.623285e+00,1.132311e+02,7.725594e+01,24039.930000,1.0

In [5]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Assuming 'data' is a pandas DataFrame with a column named 'Amount'
data = pd.read_csv(r"C:\Users\spars\OneDrive\Desktop\ADM final term\creditcard_2023.csv")

# Standardize the 'Amount' column
std_scale = StandardScaler().fit_transform(data['Amount'].values.reshape(-1, 1))
data["Amount"] = std_scale

# Display summary statistics after standardization
print(data.describe())

                  id            V1            V2            V3            V4  \
count  568630.000000  5.686300e+05  5.686300e+05  5.686300e+05  5.686300e+05
mean   284314.500000 -5.638058e-17 -1.319545e-16 -3.518788e-17 -2.879008e-17
std    164149.486121  1.000001e+00  1.000001e+00  1.000001e+00  1.000001e+00
min         0.000000 -3.495584e+00 -4.996657e+01 -3.183760e+00 -4.951222e+00
25%    142157.250000 -5.652859e-01 -4.866777e-01 -6.492987e-01 -6.560203e-01
50%    284314.500000 -9.363846e-02 -1.358939e-01  3.528579e-04 -7.376152e-02
75%    426471.750000  8.326582e-01  3.435552e-01  6.285380e-01  7.070047e-01
max    568629.000000  2.229046e+00  4.361865e+00  1.412583e+01  3.201536e+00

                 V5            V6            V7            V8            V9  \
count  5.686300e+05  5.686300e+05  5.686300e+05  5.686300e+05  5.686300e+05
mean   7.997245e-18 -3.958636e-17 -3.198898e-17  2.109273e-17  3.998623e-17
std    1.000001e+00  1.000001e+00  1.000001e+00  1.000001e+00  1.000001e+00
min   -9.952786e+00 -2.111111e+01 -4.351839e+00 -1.075634e+01 -3.751919e+00
25%   -2.934955e-01 -4.458712e-01 -2.835329e-01 -1.922572e-01 -5.687446e-01
50%    8.108788e-02  7.871758e-02  2.333659e-01 -1.145242e-01  9.252647e-02
75%    4.397368e-01  4.977881e-01  5.259548e-01  4.729905e-02  5.592621e-01
max    4.271689e+01  2.616840e+01  2.178730e+02  5.958040e+00  2.027006e+01

       ...           V21           V22           V23           V24  \
count  ...  5.686300e+05  5.686300e+05  5.686300e+05  5.686300e+05
mean   ...  4.758361e-17  3.948640e-18  6.194741e-18 -2.799036e-18
std    ...  1.000001e+00  1.000001e+00  1.000001e+00  1.000001e+00
min    ... -1.938252e+01 -7.734798e+00 -3.029545e+01 -4.067968e+00
25%    ... -1.664408e-01 -4.904892e-01 -2.376289e-01 -6.515801e-01
50%    ... -3.743065e-02 -2.732881e-02 -5.968903e-02  1.590123e-02
75%    ...  1.479787e-01  4.638817e-01  1.557153e-01  7.007374e-01
max    ...  8.087080e+00  1.263251e+01  3.170763e+01  1.296564e+01

                V25           V26           V27           V28        Amount  \
count  5.686300e+05  5.686300e+05  5.686300e+05  5.686300e+05  5.686300e+05
mean  -3.178905e-17 -7.497417e-18 -3.598760e-17  2.609101e-17 -4.021240e-16
std    1.000001e+00  1.000001e+00  1.000001e+00  1.000001e+00  1.000001e+00
min   -1.361263e+01 -8.226969e+00 -1.049863e+01 -3.903524e+01 -1.733031e+00
25%   -5.541485e-01 -6.318948e-01 -3.049607e-01 -2.318783e-01 -8.652280e-01
50%   -8.193162e-03 -1.189208e-02 -1.729111e-01 -1.392973e-02 -1.706395e-03
75%    5.500147e-01  6.728879e-01  3.340230e-01  4.095903e-01  8.662841e-01
max    1.462151e+01  5.623285e+00  1.132311e+02  7.725594e+01  1.733902e+00

          Class
count  568630.0
mean        0.5
std         0.5
min         0.0
25%         0.0
50%         0.5
75%         1.0
max         1.0

[8 rows x 31 columns]

In [6]:
data["Class"].value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
Y = data["Class"]
X = data.loc[:,"V1":"Class"]
Xtrain,Xtest,Ytrain,Ytest = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=100) 
print(Xtrain.shape)
print(Xtest.shape)
print(Ytrain.shape)
print(Ytest.shape)

(454904, 30)
(113726, 30)
(454904,)
(113726,)

# Prior Probabilities

In [8]:
prior = Ytrain.value_counts().to_list()
print(prior)
for i in range(len(prior)):
    prior[i] = prior[i]/Ytrain.shape[0]
print(prior)

[227452, 227452]
[0.5, 0.5]

# Barlett's test

In [15]:
# Handle empty input and input that is not 1d

In [14]:
import numpy as np

# Define a function to handle samples
def process_samples(samples):
    for sample in samples:
        if np.asanyarray(sample).size == 0:
            return BartlettResult(np.nan, np.nan)
        if np.asanyarray(sample).ndim > 1:
            raise ValueError('Samples must be one-dimensional.')
class BartlettResult:
    def __init__(self, value1, value2):
        self.value1 = value1
        self.value2 = value2
your_samples = [[1, 2, 3], [4, 5, 6], [], [7, 8, 9]]


result = process_samples(your_samples)
print(result)

<__main__.BartlettResult object at 0x000001979FE26A50>

In [17]:
def BoxM(*samples):
    import numpy as np
    
    g = len(samples) # the number of groups
    p = samples[0].shape[1] # the number of variables
    cov_matrix = [] # the list of covariance matrix
    freedom = [] # the list of degrees of freedom of each group 
    for i in range(g):
        cov_matrix.append(samples[i].cov()) # dataframe自带计算协方差矩阵的方法
        freedom.append(samples[i].shape[0]-1) # 样本数-1
    # 计算s_p以及后续需要用到的中间量
    s_p = 0
    total_freedom = 0
    temp = 0
    temp1 = 0
    temp2 = 0
    for i in range(g):
        s_p += freedom[i]*cov_matrix[i]
        total_freedom += freedom[i]
        temp += freedom[i]*np.log(np.linalg.det(cov_matrix[i]))
        temp1 += 1/freedom[i]
        temp2 += 1/(freedom[i]*freedom[i])
    s_p = s_p/total_freedom
    # print("s_p:",s_p)
    # 计算M
    M = total_freedom*np.log(np.linalg.det(s_p)) - temp
    # 本例中各组样本量>>20，p=29>5，g=2<5，适用于F近似
    A1 = (temp1-1/total_freedom)*(2*p*p+3*p-1)/(6*(p+1)*(g-1))
    A2 = (temp2-1/(total_freedom*total_freedom))*(p-1)*(p+2)/(6*(g-1))
    print("A1:",A1)
    print("A2:",A2)
    f1 = 1/2*(g-1)*p*(p+1)
    f2 = (f1+2)/(A2-A1*A1)
    b = f1/(1-A1-f1/f2)
    print("f1:",f1)
    print("f2:",f2)
    print("b:",b)
    from scipy import stats
    pvalue = stats.f.sf(M/b,f1,f2)
    return M/b, pvalue
print("Done")
Xtrain_0 = Xtrain[Xtrain["Class"]==0] #根据标签列获得两组的样本
Xtrain_1 = Xtrain[Xtrain["Class"]==1]
Xtrain_0 = Xtrain_0.drop('Class', axis=1) #删除标签列
Xtrain_1 = Xtrain_1.drop('Class', axis=1)
M_stastic, p_value = BoxM(Xtrain_0,Xtrain_1)
print(M_stastic)
print(p_value)

Done
A1: 6.477585648483996e-05
A2: 4.8936265343925344e-09
f1: 435.0
f2: 626330279068.3167
b: 435.0281796250668
10508.947835603269
0.0

# Estimate the parameters of the conditional probability density functions and Compute discriminant functions

In [18]:
class DiscriminationAnalysis():
    def __init__(self,prior):
        self.prior = prior
        self.s_0 = None
        self.mean_0 = None
        self.s_1 = None
        self.mean_1 = None
        self.classification_result = []
    def fit(self,X,Y):
        full = pd.concat([X,Y],axis=1,ignore_index=False)
        full_0 = full[full["Class"]==0] 
        full_1 = full[full["Class"]==1]
        X_0 = full_0.drop('Class', axis=1) 
        X_1 = full_1.drop('Class', axis=1)
        self.s_0 = X_0.cov()
        self.mean_0 = X_0.mean(axis=0)
        self.s_1 = X_1.cov()
        self.mean_1 = X_1.mean(axis=0)
    def classification(self,row):
        x = np.array(row)
        Q_score_0 = -1/2*np.log(np.linalg.det(self.s_0))-1/2*np.dot(np.dot((x-self.mean_0).T, np.linalg.inv(self.s_0)), (x-self.mean_0))+np.log(self.prior[0])
        Q_score_1 = -1/2*np.log(np.linalg.det(self.s_1))-1/2*np.dot(np.dot((x-self.mean_1).T, np.linalg.inv(self.s_1)), (x-self.mean_1))+np.log(self.prior[1])
        if Q_score_0 > Q_score_1:
            self.classification_result.append(0)
        else:
            self.classification_result.append(1)
    def score(self,X,Y):
        self.classification_result.clear()
        print(len(self.classification_result))
        X.apply(self.classification,axis=1)
        print(len(self.classification_result))
        right = 0
        for i in range(X.shape[0]):
            if self.classification_result[i] == Y.iloc[i]:
                right += 1
        return right/X.shape[0]

In [19]:
DA = DiscriminationAnalysis(prior)
if "Class" in Xtrain.columns:
    Xtrain = Xtrain.drop("Class",axis=1)
full_train_valid = pd.concat([Xtrain,Ytrain],axis=1,ignore_index=False)
train_valid_0 = full_train_valid[full_train_valid["Class"]==0] 
train_valid_1 = full_train_valid[full_train_valid["Class"]==1]

accuracy_list =[]
num_0 = train_valid_0.shape[0]
num_1 = train_valid_1.shape[0]
for i in range(4):    
    sample_valid_0 = train_valid_0[int(num_0/4*i):int(num_0/4*(i+1))]
    sample1_0 = train_valid_0[:int(num_0/4*i)]
    sample2_0 = train_valid_0[int(num_0/4*(i+1)):]
    sample_train_0 = pd.concat([sample1_0,sample2_0],axis=0,ignore_index=False)
    sample_valid_1 = train_valid_1[int(num_1/4*i):int(num_1/4*(i+1))]
    sample1_1 = train_valid_1[:int(num_1/4*i)]
    sample2_1 = train_valid_1[int(num_1/4*(i+1)):]
    sample_train_1 = pd.concat([sample1_1,sample2_1],axis=0,ignore_index=False)
    
    sample_train_01 = pd.concat([sample_train_0,sample_train_1],axis=0,ignore_index=False) 
    sample_valid_01 = pd.concat([sample_valid_0,sample_valid_1],axis=0,ignore_index=False) 
    sample_train_y = sample_train_01["Class"]
    sample_train_x = sample_train_01.drop("Class",axis=1)
    sample_valid_y = sample_valid_01["Class"]
    sample_valid_x = sample_valid_01.drop("Class",axis=1)

    
    DA.fit(sample_train_x,sample_train_y)
    accuracy = DA.score(sample_valid_x,sample_valid_y)
    accuracy_list.append(accuracy)
print(accuracy_list)

0
113726
0
113726
0
113726
0
113726
[0.9512600460756555, 0.9513128044598421, 0.9519195258779874, 0.9514359073562774]

# Classify observations with unknown group memberships

In [20]:
DA = DiscriminationAnalysis(prior)
if "Class" in Xtrain.columns:
    Xtrain = Xtrain.drop("Class",axis=1)
DA.fit(Xtrain,Ytrain)
if "Class" in Xtest.columns:
    Xtest = Xtest.drop("Class",axis=1)
DA.score(Xtest,Ytest)

0
113726

0.9520162495823294